// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/22/2025, 8:41:23 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/macos/Desktop/senior/testdrive2/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","/Users/macos/Desktop/senior/testdrive2/layouts/**/*.{vue,js,mjs}","/Users/macos/Desktop/senior/testdrive2/pages/**/*.{vue,js,mjs}","/Users/macos/Desktop/senior/testdrive2/composables/**/*.{js,ts,mjs}","/Users/macos/Desktop/senior/testdrive2/utils/**/*.{js,ts,mjs}","/Users/macos/Desktop/senior/testdrive2/{A,a}pp.{vue,js,mjs}","/Users/macos/Desktop/senior/testdrive2/{E,e}rror.{vue,js,mjs}","/Users/macos/Desktop/senior/testdrive2/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;